version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.62
    - 1.16.63
    - 1.17.0
    - 1.17.1
    - 1.17.12
    - 1.17.13
    - 1.17.15
    - 1.17.2
    - 1.17.20
    - 1.17.21
    - 1.17.24
    - 1.17.25
    - 1.17.26
    - 1.17.28
    - 1.17.29
    - 1.17.3
    - 1.17.30
    - 1.17.32
    - 1.17.33
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.38
    - 1.17.39
    - 1.17.4
    - 1.17.40
    - 1.17.41
    - 1.17.43
    - 1.17.44
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.48
    - 1.17.49
    - 1.17.5
    - 1.17.50
    - 1.17.51
    - 1.17.52
    - 1.17.53
    - 1.17.54
    - 1.17.55
    - 1.17.56
    - 1.17.57
    - 1.17.58
    - 1.17.59
    - 1.17.6
    - 1.17.8
    - 1.17.9
  - dependency-name: requests-mock
    versions:
    - 1.9.0
  - dependency-name: pylint
    versions:
    - 2.6.1
    - 2.7.0
    - 2.7.4
    - 2.8.1
  - dependency-name: moto
    versions:
    - 2.0.3
    - 2.0.4
  - dependency-name: apache-airflow
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: cryptography
    versions:
    - 3.3.2
    - 3.4.6
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
