version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
