language: python
python:
  - "3.6"

# install dependencies
install:
  - pip install pipenv
  - SLUGIFY_USES_TEXT_UNIDECODE=yes pipenv install --dev

# lint & run tests
script:
  - pipenv run pylint cob_datapipeline -E
  # - script: pipenv run pytest

after_success:
  - true

# deploy qa, stage, prod via ansible
deploy:
  - provider: script
    script: bash .travis/deploy-qa.sh
    on:
      branch: qa
  - provider: script
    script: bash .travis/deploy-master.sh
    on:
      branch: master
