language: python
python:
- '3.6'
install:
- pip install pipenv
- SLUGIFY_USES_TEXT_UNIDECODE=yes pipenv install --dev
script:
- pipenv run pylint cob_datapipeline -E
after_success:
- true
before_deploy:
- openssl aes-256-cbc -K $encrypted_ffb341899730_key -iv $encrypted_ffb341899730_iv -in .travis/deploy.zip.enc -out .travis/deploy.zip -d
- unzip .travis/deploy.zip -d .travis
- mv .travis/.gritty_travis ~/.ssh/.gritty_travis
- mv .travis/.conan_the_deployer ~/.ssh/.conan_the_deployer
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/.gritty_travis
- chmod 600 ~/.ssh/.conan_the_deployer
- echo -e "Host $QA_SERVER\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/.conan_the_deployer\n" >> ~/.ssh/config
- echo -e "Host $STAGE_SERVER\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/.conan_the_deployer\n" >> ~/.ssh/config
- echo -e "Host $PROD_SERVER\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/.conan_the_deployer\n" >> ~/.ssh/config
- echo -e "HOST gitserv\n\tHostname remote.server.com\n\tIdentityFile ~/.ssh/.gritty_travis\n\tIdentitiesOnly yes\n" >> ~/.ssh/config
- ssh-add ~/.ssh/.gritty_travis
- ssh-add ~/.ssh/.conan_the_deployer
deploy:
- provider: script
  script: bash .travis/deploy-qa.sh
  on:
    branch: qa
- provider: script
  script: bash .travis/deploy-stage.sh
  on:
    branch: master
- provider: script
  script: bash .travis/deploy-prod.sh
  on:
    branch: master
    tags: true

notifications:
  slack:
    rooms:
      - secure: SDncKtH2PvP4q1sJDL/m0oJNaE78Ye0S2yQGmVOE71/a0ShzKCzt+Pa6SaklKspdcrD7D1AtgwJGwkQhxaqXtDDRI4WyYjCIi2I7VHy5drnzEddtpAi4mPedoqEC8m6lQbsmKewQFq5uFCQYetp7YHV675B3noOnGbWw0t3s0UVn17XV7G2zk3a6l4H9Rj7dM9eSbcSTl+vWoHA93ZoQpId278ZV4cTbL0lXvhAueTM1FCKAZxArHMRa3UA4ocDsO9tqiKK96Gf4qzcVzYAhc9tW2Tx/9wjvsAAKxRpdWjQ5n1oMX+oAhSIocxn9p3ye8GZ5OwgB3acigPcKt8foc6SuYrX2Ppu/s3BdJz9AK/fiRdqtpEu1PiQAbsAdhatGh2OolvaymR9LQ4NVLk+xvctUANS5TeFEnIfEl73SxPwh844PznwKiTFSvN/XAd+39R1BNHJopGgJfzaObODgI8uKtqQA4UPVxyuB3PfWAqUGJKRecqu9yaGnQhqqZdyL+o4GXqWBdXaRXwdRHtmwpbFa71RnjyWttOIMKxQhKTVhOtcAuuu3qwj+Z7q7hrxMwkL/Xq4gJ5jbfzcWbN/Tik47YXLppIOYT+57i1QeQAokHarE5/0/RhBMwn9mWqcP77IE8h+FAMaVtdOQbbULYGluhpHgENXL9f/FIDEZp/A=
    on_success: always
    on_failure: always
