language: python
python:
  - "3.6"

# install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

# lint & code review (errors only for now)
script:
  - pipenv run pylint cob_datapipeline -E

# run tests & generate coverage
script:
  - pipenv run pytest
