language: python
python:
  - "3.7"

# install dependencies
install:
  - pip install pipenv
  - SLUGIFY_USES_TEXT_UNIDECODE=yes pipenv install --dev

# lint & code review
script:
  - pipenv run pylint cob_datapipeline

# run tests & generate coverage
script:
  - pipenv run pytest
